2024-06-13 16:34:42,601 ERROR Internal Server Error: / C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\utils\log.py (<class 'TypeError'>, TypeError("debug() missing 1 required positional argument: 'msg'"), <traceback object at 0x0000013033346240>)
Traceback (most recent call last):
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\79895\PycharmProjects\NewsPortalProject\news_portal\my_news_portal\views.py", line 28, in get_queryset
    logger.debug()
TypeError: debug() missing 1 required positional argument: 'msg'
2024-06-13 16:34:42,605 ERROR "GET / HTTP/1.1" 500 91726 C:\Users\79895\PycharmProjects\NewsPortalProject\venv\lib\site-packages\django\core\servers\basehttp.py None
